JNG-4702 Update tutorial documentation for newer version of SDK
BlackBeltTechnology/judo-community-documentation pull request #18
Opened 2023-10-24 16:54 UTC by gaborflorian

2023-10-30 09:23 UTC, Madmat8 approved these changes

2023-10-30 13:04 UTC, noherczeg requested changes

2023-10-30 13:04 UTC, noherczeg commented on docs/modules/ROOT/pages/java-sdk/01_entity_module.adoc
> + * Without parameter `.execute()`, you will gain all elements, that satisfy the query critics.
"critics"??

2023-10-30 13:04 UTC, noherczeg commented on docs/modules/ROOT/pages/java-sdk/01_entity_module.adoc
> +If you don't need the instances of the entity, only the count of the fitted entities, you can use the `count` methods.
"fitted"??

2023-10-30 13:04 UTC, noherczeg commented on docs/modules/ROOT/pages/java-sdk/01_entity_module.adoc
> +To understand how to use the `required` modifier, please check the xref:meta-jsl:05_entity.adoc#primitive-field[Primitive Fields,window=_blank]
There is no point in removing the empty line, please put it back.

2023-10-30 13:04 UTC, noherczeg commented on docs/modules/ROOT/pages/java-sdk/01_entity_module.adoc
> +You can get the ancestors representation of the Person entity if you need it. Use the `adaptTo(Class<T> target)` method.
ancestor of

2023-10-30 13:04 UTC, noherczeg commented on docs/modules/ROOT/pages/java-sdk/01_entity_module.adoc
> +This method cast the actual element to the target class.
casts

2023-10-30 13:04 UTC, noherczeg commented on docs/modules/ROOT/pages/java-sdk/01_entity_module.adoc
> +Each DAO has its own Identifier class, so if you want to use the CustomerDAO to retrieve a Person as a Customer, you'll need to adapt them.
adapt it

2023-10-30 13:04 UTC, noherczeg commented on docs/modules/ROOT/pages/java-sdk/01_entity_module.adoc
> +Only use this method if there is an inherited relation between the entities.
Does the language throw errors if there is no relation? If not is it intended? If it does, then we do not need this note IMO.

2023-10-30 13:04 UTC, noherczeg commented on docs/modules/ROOT/pages/java-sdk/01_entity_module.adoc
> +* calculated members
calculated?? :D

2023-10-30 13:04 UTC, noherczeg commented on docs/modules/ROOT/pages/java-sdk/01_entity_module.adoc
> +When creating an entity with relations, you attach it using the `PersonAttachedRelationsForCreate`. This builder contains all the relations that the Person entity has, including the inherited ones.
attach them

2023-10-30 13:04 UTC, noherczeg commented on docs/modules/ROOT/pages/java-sdk/01_entity_module.adoc
> +    Person johnPerson = personDao.create(Person.builder()
There is no `personDao`injected.

2023-10-30 13:04 UTC, noherczeg commented on docs/modules/ROOT/pages/java-sdk/01_entity_module.adoc
> +The `.setFavourite()` can only set existing Order elements.
What is `setFavourite` ? we haven't referenced it in the example code.

2023-10-30 13:04 UTC, noherczeg commented on docs/modules/ROOT/pages/java-sdk/01_entity_module.adoc
> +    relation required Customer customer: opposite orders;
I hope this is a typo here

2023-10-30 13:04 UTC, noherczeg commented on docs/modules/ROOT/pages/java-sdk/01_entity_module.adoc
> +    Product butter = productDao.create(Product.builder().withName("Butter").withPrice(2).build());
There is no `productDao` wired in...

2023-10-30 13:04 UTC, noherczeg commented on docs/modules/ROOT/pages/java-sdk/01_entity_module.adoc
> +    Person johnPerson = personDao.create(Person.builder()
There is no `personDao` wired in.

2023-10-30 13:04 UTC, noherczeg commented on docs/modules/ROOT/pages/java-sdk/01_entity_module.adoc
> +    orderDao.setCustomer(order, /* existent customer */);
If we have `customerForOrder` created just 1 line above, why not add it to the params?

2023-10-30 13:04 UTC, noherczeg commented on docs/modules/ROOT/pages/java-sdk/01_entity_module.adoc
> +You can influence the behavior of a field or a relation. You have the flexibility to fetch a field like a relation, or vice versa.
Vice versa what? We only have a single example.

2023-10-30 13:04 UTC, noherczeg commented on docs/modules/ROOT/pages/java-sdk/01_entity_module.adoc
> +    //TODO this is required
Why do we need this TODO block?

2023-10-30 13:04 UTC, noherczeg commented on docs/modules/ROOT/pages/java-sdk/01_entity_module.adoc
> +	field String productName <= self.product.name eager: false;
Is `eager` false by default? If so why specify it?

2023-10-30 13:04 UTC, noherczeg commented on docs/modules/ROOT/pages/java-sdk/01_entity_module.adoc
> +	field String productName <= self.product.name eager: false;
Ummm.... primitive fields can be eager/lazy???

2023-10-30 13:04 UTC, noherczeg commented on docs/modules/ROOT/pages/java-sdk/01_entity_module.adoc
> +Parameterless static queries are generated on their corresponding dedicated DAOs and contains an `.execute()` method.
contain.

2023-10-30 13:04 UTC, noherczeg commented on docs/modules/ROOT/pages/java-sdk/01_entity_module.adoc
> +* Collections: start with "query", and parameters can be set on it. After that you must trigger with the `.execute()` method.
set on them. Since queries are builders, we need to call the `.execute()` method in order to get the actual results.

2023-10-30 13:04 UTC, noherczeg commented on docs/modules/ROOT/pages/java-sdk/01_entity_module.adoc
> +* Single references, or primitives: contains an `.execute()`, and parameters can be set on the same method.
contain

2023-10-30 16:28 UTC, gaborflorian commented on docs/modules/ROOT/pages/java-sdk/01_entity_module.adoc
> +* Single references, or primitives: contains an `.execute()`, and parameters can be set on the same method.
[217e15a](https://github.com/BlackBeltTechnology/judo-community-documentation/pull/18/commits/217e15ac8d6d09a1d404ad7e8f21cf6803aa697f)

2023-10-30 16:28 UTC, gaborflorian commented on docs/modules/ROOT/pages/java-sdk/01_entity_module.adoc
> +* Collections: start with "query", and parameters can be set on it. After that you must trigger with the `.execute()` method.
[217e15a](https://github.com/BlackBeltTechnology/judo-community-documentation/pull/18/commits/217e15ac8d6d09a1d404ad7e8f21cf6803aa697f)

2023-10-30 16:28 UTC, gaborflorian commented on docs/modules/ROOT/pages/java-sdk/01_entity_module.adoc
> +Parameterless static queries are generated on their corresponding dedicated DAOs and contains an `.execute()` method.
[217e15a](https://github.com/BlackBeltTechnology/judo-community-documentation/pull/18/commits/217e15ac8d6d09a1d404ad7e8f21cf6803aa697f)

2023-10-30 16:28 UTC, gaborflorian commented on docs/modules/ROOT/pages/java-sdk/01_entity_module.adoc
> +	field String productName <= self.product.name eager: false;
Rewrited 
[217e15a](https://github.com/BlackBeltTechnology/judo-community-documentation/pull/18/commits/217e15ac8d6d09a1d404ad7e8f21cf6803aa697f)

2023-10-30 16:29 UTC, gaborflorian commented on docs/modules/ROOT/pages/java-sdk/01_entity_module.adoc
> +    //TODO this is required
[217e15a](https://github.com/BlackBeltTechnology/judo-community-documentation/pull/18/commits/217e15ac8d6d09a1d404ad7e8f21cf6803aa697f)

2023-10-30 16:29 UTC, gaborflorian commented on docs/modules/ROOT/pages/java-sdk/01_entity_module.adoc
> +You can influence the behavior of a field or a relation. You have the flexibility to fetch a field like a relation, or vice versa.
Rewrited, only relation can be eager/lazy

2023-10-30 16:29 UTC, gaborflorian commented on docs/modules/ROOT/pages/java-sdk/01_entity_module.adoc
> +You can influence the behavior of a field or a relation. You have the flexibility to fetch a field like a relation, or vice versa.
[217e15a](https://github.com/BlackBeltTechnology/judo-community-documentation/pull/18/commits/217e15ac8d6d09a1d404ad7e8f21cf6803aa697f)

2023-10-30 16:29 UTC, gaborflorian commented on docs/modules/ROOT/pages/java-sdk/01_entity_module.adoc
> +This method cast the actual element to the target class.
[217e15a](https://github.com/BlackBeltTechnology/judo-community-documentation/pull/18/commits/217e15ac8d6d09a1d404ad7e8f21cf6803aa697f)

2023-10-30 16:29 UTC, gaborflorian commented on docs/modules/ROOT/pages/java-sdk/01_entity_module.adoc
> +You can get the ancestors representation of the Person entity if you need it. Use the `adaptTo(Class<T> target)` method.
[217e15a](https://github.com/BlackBeltTechnology/judo-community-documentation/pull/18/commits/217e15ac8d6d09a1d404ad7e8f21cf6803aa697f)

2023-10-30 16:29 UTC, gaborflorian commented on docs/modules/ROOT/pages/java-sdk/01_entity_module.adoc
> +    orderDao.setCustomer(order, /* existent customer */);
[217e15a](https://github.com/BlackBeltTechnology/judo-community-documentation/pull/18/commits/217e15ac8d6d09a1d404ad7e8f21cf6803aa697f)

2023-10-30 16:29 UTC, gaborflorian commented on docs/modules/ROOT/pages/java-sdk/01_entity_module.adoc
> +    Product butter = productDao.create(Product.builder().withName("Butter").withPrice(2).build());
[217e15a](https://github.com/BlackBeltTechnology/judo-community-documentation/pull/18/commits/217e15ac8d6d09a1d404ad7e8f21cf6803aa697f)

2023-10-30 16:30 UTC, gaborflorian commented on docs/modules/ROOT/pages/java-sdk/01_entity_module.adoc
> +    Person johnPerson = personDao.create(Person.builder()
[217e15a](https://github.com/BlackBeltTechnology/judo-community-documentation/pull/18/commits/217e15ac8d6d09a1d404ad7e8f21cf6803aa697f)

2023-10-30 16:30 UTC, gaborflorian commented on docs/modules/ROOT/pages/java-sdk/01_entity_module.adoc
> +    relation required Customer customer: opposite orders;
Yes it is

2023-10-30 16:30 UTC, gaborflorian commented on docs/modules/ROOT/pages/java-sdk/01_entity_module.adoc
> +    relation required Customer customer: opposite orders;
[217e15a](https://github.com/BlackBeltTechnology/judo-community-documentation/pull/18/commits/217e15ac8d6d09a1d404ad7e8f21cf6803aa697f)

2023-10-30 16:30 UTC, gaborflorian commented on docs/modules/ROOT/pages/java-sdk/01_entity_module.adoc
> +The `.setFavourite()` can only set existing Order elements.
Add example for it

2023-10-30 16:30 UTC, gaborflorian commented on docs/modules/ROOT/pages/java-sdk/01_entity_module.adoc
> +The `.setFavourite()` can only set existing Order elements.
[217e15a](https://github.com/BlackBeltTechnology/judo-community-documentation/pull/18/commits/217e15ac8d6d09a1d404ad7e8f21cf6803aa697f)

2023-10-30 16:30 UTC, gaborflorian commented on docs/modules/ROOT/pages/java-sdk/01_entity_module.adoc
> +* calculated members
[217e15a](https://github.com/BlackBeltTechnology/judo-community-documentation/pull/18/commits/217e15ac8d6d09a1d404ad7e8f21cf6803aa697f)

2023-10-30 16:30 UTC, gaborflorian commented on docs/modules/ROOT/pages/java-sdk/01_entity_module.adoc
> +When creating an entity with relations, you attach it using the `PersonAttachedRelationsForCreate`. This builder contains all the relations that the Person entity has, including the inherited ones.
[217e15a](https://github.com/BlackBeltTechnology/judo-community-documentation/pull/18/commits/217e15ac8d6d09a1d404ad7e8f21cf6803aa697f)

2023-10-30 16:31 UTC, gaborflorian commented on docs/modules/ROOT/pages/java-sdk/01_entity_module.adoc
> + * Without parameter `.execute()`, you will gain all elements, that satisfy the query critics.
[217e15a](https://github.com/BlackBeltTechnology/judo-community-documentation/pull/18/commits/217e15ac8d6d09a1d404ad7e8f21cf6803aa697f)

2023-10-30 16:31 UTC, gaborflorian commented on docs/modules/ROOT/pages/java-sdk/01_entity_module.adoc
> +If you don't need the instances of the entity, only the count of the fitted entities, you can use the `count` methods.
[217e15a](https://github.com/BlackBeltTechnology/judo-community-documentation/pull/18/commits/217e15ac8d6d09a1d404ad7e8f21cf6803aa697f)

2023-10-30 16:32 UTC, gaborflorian commented on docs/modules/ROOT/pages/java-sdk/01_entity_module.adoc
> +To understand how to use the `required` modifier, please check the xref:meta-jsl:05_entity.adoc#primitive-field[Primitive Fields,window=_blank]
[217e15a](https://github.com/BlackBeltTechnology/judo-community-documentation/pull/18/commits/217e15ac8d6d09a1d404ad7e8f21cf6803aa697f)

2023-10-30 16:32 UTC, gaborflorian commented on docs/modules/ROOT/pages/java-sdk/01_entity_module.adoc
> +Each DAO has its own Identifier class, so if you want to use the CustomerDAO to retrieve a Person as a Customer, you'll need to adapt them.
[217e15a](https://github.com/BlackBeltTechnology/judo-community-documentation/pull/18/commits/217e15ac8d6d09a1d404ad7e8f21cf6803aa697f)

2023-10-30 16:38 UTC, gaborflorian commented on docs/modules/ROOT/pages/java-sdk/01_entity_module.adoc
> +Only use this method if there is an inherited relation between the entities.
This cast does not occur on the database side. It is up to the developer to decide how to use it correctly.

2023-10-30 16:39 UTC, gaborflorian commented on docs/modules/ROOT/pages/java-sdk/01_entity_module.adoc
> +Only use this method if there is an inherited relation between the entities.
[217e15a](https://github.com/BlackBeltTechnology/judo-community-documentation/pull/18/commits/217e15ac8d6d09a1d404ad7e8f21cf6803aa697f)

2023-10-31 11:37 UTC, noherczeg approved these changes

2023-10-31 11:43 UTC, bencegelei requested changes

2023-10-31 11:43 UTC, bencegelei commented on docs/modules/ROOT/pages/java-sdk/01_entity_module.adoc
> +    );
Is this signature valid? `createOrderItems(order, list of items, list of relations of items)`?

2023-10-31 11:43 UTC, bencegelei commented on docs/modules/ROOT/pages/java-sdk/01_entity_module.adoc
> +// TODO Deep copy explanation
Please add a JIRA ticket here

2023-10-31 11:43 UTC, bencegelei commented on docs/modules/ROOT/pages/java-sdk/01_entity_module.adoc
> +    orderDao.setCustomer(order, customerForOrder.get());
Please remove Optional wrapping here. It's unnecessary the way it's used in this case.

2023-10-31 11:43 UTC, bencegelei commented on docs/modules/ROOT/pages/java-sdk/01_entity_module.adoc
> +* `Person queryBestFriend(Person object)` return type `Optional<Person>`
Does `Person queryBestFriend(Person object)` return Optional<Person>? 

Shouldn't it be `Optional<Person> queryBestFriend(Person object)`? "return" part can also be deleted then.

2023-10-31 11:43 UTC, bencegelei commented on docs/modules/ROOT/pages/java-sdk/01_entity_module.adoc
> +* `Animal queryPet(Person object)` return type `Person`
Same as with queryBestFriend

2023-10-31 11:43 UTC, bencegelei commented on docs/modules/ROOT/pages/java-sdk/01_entity_module.adoc
> +    // the calculated member didn't changed
the calculated member hasn't changed

2023-10-31 11:43 UTC, bencegelei commented on docs/modules/ROOT/pages/java-sdk/01_entity_module.adoc
> +The query's return depends on the JSL types:
> The query's return depends on the JSL types:

Queries' return type depend on the following query types in JSL:

2023-10-31 11:43 UTC, bencegelei commented on docs/modules/ROOT/pages/java-sdk/01_entity_module.adoc
> +Parameterless static queries are generated on their corresponding dedicated DAOs and contain an `.execute()` method.
Execute is only generated for queries with list return types, isn't it? 
Or is it only the case for relations?

2023-10-31 11:58 UTC, gaborflorian commented on docs/modules/ROOT/pages/java-sdk/01_entity_module.adoc
> +Parameterless static queries are generated on their corresponding dedicated DAOs and contain an `.execute()` method.
It is only the case for collection relations.

  *  Primitive queries will return the primitive type representation.
  *  Single-entity queries will return an Optional within the Entity class.
  *  List-entity queries will return a QueryCustomizer.

2023-10-31 11:58 UTC, gaborflorian commented on docs/modules/ROOT/pages/java-sdk/01_entity_module.adoc
> +* `Animal queryPet(Person object)` return type `Person`
The return type `Person` is unnecessary

2023-10-31 11:58 UTC, gaborflorian commented on docs/modules/ROOT/pages/java-sdk/01_entity_module.adoc
> +* `Person queryBestFriend(Person object)` return type `Optional<Person>`
Yes this is a mistake here

2023-10-31 11:59 UTC, gaborflorian commented on docs/modules/ROOT/pages/java-sdk/01_entity_module.adoc
> +    );
For now, yes. In the future, we will package the builder and attachments into a single object.

2023-10-31 12:02 UTC, gaborflorian commented on docs/modules/ROOT/pages/java-sdk/01_entity_module.adoc
> +    orderDao.setCustomer(order, customerForOrder.get());
[dfc5609](https://github.com/BlackBeltTechnology/judo-community-documentation/pull/18/commits/dfc56094e1304ec0c7a436bde210e70dca4e5dd1)

2023-10-31 12:02 UTC, gaborflorian commented on docs/modules/ROOT/pages/java-sdk/01_entity_module.adoc
> +* `Person queryBestFriend(Person object)` return type `Optional<Person>`
[dfc5609](https://github.com/BlackBeltTechnology/judo-community-documentation/pull/18/commits/dfc56094e1304ec0c7a436bde210e70dca4e5dd1)

2023-10-31 12:02 UTC, gaborflorian commented on docs/modules/ROOT/pages/java-sdk/01_entity_module.adoc
> +* `Animal queryPet(Person object)` return type `Person`
[dfc5609](https://github.com/BlackBeltTechnology/judo-community-documentation/pull/18/commits/dfc56094e1304ec0c7a436bde210e70dca4e5dd1)

2023-10-31 12:02 UTC, gaborflorian commented on docs/modules/ROOT/pages/java-sdk/01_entity_module.adoc
> +    // the calculated member didn't changed
[dfc5609](https://github.com/BlackBeltTechnology/judo-community-documentation/pull/18/commits/dfc56094e1304ec0c7a436bde210e70dca4e5dd1)

2023-10-31 12:03 UTC, gaborflorian commented on docs/modules/ROOT/pages/java-sdk/01_entity_module.adoc
> +The query's return depends on the JSL types:
[dfc5609](https://github.com/BlackBeltTechnology/judo-community-documentation/pull/18/commits/dfc56094e1304ec0c7a436bde210e70dca4e5dd1)

2023-10-31 12:03 UTC, gaborflorian commented on docs/modules/ROOT/pages/java-sdk/01_entity_module.adoc
> +// TODO Deep copy explanation
[199b002](https://github.com/BlackBeltTechnology/judo-community-documentation/pull/18/commits/199b00232e3f87838656ffe666b36ed85b88d793)

2023-10-31 12:14 UTC, bencegelei commented on docs/modules/ROOT/pages/java-sdk/01_entity_module.adoc
> +Parameterless static queries are generated on their corresponding dedicated DAOs and contain an `.execute()` method.
I know about the return types. I meant the execute method itself because in case of single queryies, calling querySomething method expects the parameters instead of execute and execution is not required because there is no query customizer there.

2023-10-31 12:17 UTC, gaborflorian commented on docs/modules/ROOT/pages/java-sdk/01_entity_module.adoc
> +    );
User
For now yes, in the future will change, we will packege the builder, and attachments in a one object

2023-10-31 12:30 UTC, gaborflorian commented on docs/modules/ROOT/pages/java-sdk/01_entity_module.adoc
> +Parameterless static queries are generated on their corresponding dedicated DAOs and contain an `.execute()` method.
[1e77ef8](https://github.com/BlackBeltTechnology/judo-community-documentation/pull/18/commits/1e77ef8141a4dbddcb659114250431a1696d444c)

2023-10-31 12:31 UTC, bencegelei commented on docs/modules/ROOT/pages/java-sdk/01_entity_module.adoc
> +    );
What if let's say I write this:

    createOrderItems(
        order,
        List.of(Item.builder().withName("item1").build(), Item.builder().withName("item2").build()),
        List.of(product1, product2)
    )

`product1` is set to `item1` and `product2` is set to `item2` ?

2023-10-31 12:32 UTC, bencegelei commented on docs/modules/ROOT/pages/java-sdk/01_entity_module.adoc
> +    );
And what happens in case of:

    createOrderItems(
        order,
        List.of(Item.builder().withName("item1").build(), Item.builder().withName("item2").build()),
        List.of(product2)
    )

2023-10-31 14:23 UTC, bencegelei approved these changes

2023-11-02 08:51 UTC, robertcsakany approved these changes

2023-12-15 16:47 UTC, merged